// src/app/terms/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Use — MyCETReviewer',
  description: 'Terms and conditions for using MyCETReviewer.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="sticky top-0 z-50 bg-white/95 backdrop-blur-sm border-b border-gray-100">
        <div className="max-w-2xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="text-sm text-gray-500 hover:text-gray-900">← Home</Link>
          <span className="font-black text-gray-900">MyCET<span className="text-red-600">Reviewer</span></span>
          <div/>
        </div>
      </nav>

      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-10">
        <h1 className="text-3xl font-black text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: May 2026</p>

        <div className="space-y-8 text-sm text-gray-700 leading-relaxed">
          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">1. Acceptance</h2>
            <p>By accessing or using MyCETReviewer ("the Platform"), you agree to these Terms of Use. If you do not agree, please do not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">2. Description of service</h2>
            <p>MyCETReviewer provides AI-generated practice questions, diagnostic exams, mock exams, and study plans for Philippine college entrance tests including UPCAT, ACET, DCAT, USTET, PUPCET, and State U CET. The Platform is for personal, non-commercial study use only.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">3. Accounts</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must provide a valid email address to create an account.</li>
              <li>You are responsible for maintaining the security of your account.</li>
              <li>One account per person. Multiple accounts are not permitted.</li>
              <li>You must be at least 13 years old to create an account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">4. Payment and access</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Full access costs ₱500 as a one-time payment valid for 1 year from activation.</li>
              <li>Payment is accepted via GCash or Instapay. Access is activated after manual verification, typically within 5 minutes.</li>
              <li>Payments are non-refundable once access has been activated.</li>
              <li>We reserve the right to revoke access for violations of these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">5. Acceptable use</h2>
            <p className="mb-2">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Share your account credentials with others</li>
              <li>Copy, redistribute, or sell content from the Platform</li>
              <li>Use automated tools to scrape or extract questions</li>
              <li>Attempt to reverse-engineer or tamper with the Platform</li>
              <li>Use the Platform for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">6. AI-generated content</h2>
            <p>Questions and study plans are generated by AI and are intended for practice purposes only. While we verify questions for accuracy, we do not guarantee that all content is error-free or matches the exact format of actual entrance exams. MyCETReviewer is not affiliated with UP, Ateneo, De La Salle, UST, PUP, or any other institution.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">7. Intellectual property</h2>
            <p>All Platform content, design, and code are owned by MyCETReviewer. You may not copy or reproduce any part of the Platform without written permission.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">8. Disclaimer</h2>
            <p>The Platform is provided "as is" without warranties of any kind. We do not guarantee that using MyCETReviewer will result in passing any entrance exam. Results depend on your effort and preparation.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">9. Limitation of liability</h2>
            <p>MyCETReviewer shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Platform. Our total liability shall not exceed the amount you paid for access.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">10. Termination</h2>
            <p>We may suspend or terminate your account for violations of these terms. You may cancel your account at any time by emailing us. Termination does not entitle you to a refund.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">11. Governing law</h2>
            <p>These terms are governed by the laws of the Republic of the Philippines.</p>
          </section>

          <section>
            <h2 className="text-base font-black text-gray-900 mb-2">12. Contact</h2>
            <p>Questions? Email <a href="mailto:hello@mycetreviewer.com" className="text-red-600 hover:underline">hello@mycetreviewer.com</a> or use our <Link href="/contact" className="text-red-600 hover:underline">contact form</Link>.</p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-gray-100 flex gap-4 text-xs text-gray-400">
          <Link href="/privacy" className="hover:text-gray-600">Privacy Policy</Link>
          <Link href="/contact" className="hover:text-gray-600">Contact</Link>
          <Link href="/" className="hover:text-gray-600">Home</Link>
        </div>
      </div>
    </div>
  )
}
